name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  GITHUB_TOKEN:
    description: 'A github token'
    required: true
runs:
  using: 'node24'
  main: 'dist/index.js'
