name: test run
on: # rebuild any PRs and main branch changes
  pull_request:

jobs:
  test: # make sure the action works on a clean machine without building
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.PAT_REPO }}
